server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://postgres:5432/post
    username: alkoscode
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true